apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: multimaxx-platform
manifests:
  rawYaml:
    # Deploy database resources first
    - ./k8s/db/*.yaml
    # Deploy service and deployment resources next
    - ./k8s/services/*.yaml
    # Deploy ingress resources last
    - ./k8s/nginx/*.yaml
build:
  artifacts:
    - image: georgiiparla/auth
      context: ./auth
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl: {}
