apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: multimaxx-platform
manifests:
  rawYaml:
    - ./k8s/*.yaml
build:
  artifacts:
    - image: georgiiparla/auth
      context: ./auth
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl: {}
