apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: multimaxx-platform
manifests:
  rawYaml:
    - ./k8s/db/*.yaml
    - ./k8s/services/*.yaml
    - ./k8s/nginx/*.yaml
build:
  artifacts:
    - image: georgiiparla/auth
      context: ./auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: georgiiparla/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.{ts,tsx,jsx}'
            dest: .
deploy:
  kubectl: {}
